version: '3.9'

services:
  banco_dos_amigos:
    container_name: banco_dos_amigos_db
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
